env: conf3
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: sell_well
      url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
girl:
  name: wanghy
  age: 19
